### ISSUE TITLE
"exclude pages" for TOC+ widget?

### ISSUE THREAD

**Issue by hellt** [zedzedzed/table-of-contents-plus#111]
Hi there,
I am loving toc+ widget which shows my index in a sidebar, though it appears not only in posts but even in categories pages like `<site_name>/category/<category_name>`
Is it possible to limit scope of toc+ widget to only posts pages?

**Comment by zedzedzed** [comment]
Try one of these?
http://www.wpstarted.com/wordpress-select-widgets-to-show/
