### ISSUE TITLE
Unable to override minimum number of headers from the shortcode

### ISSUE THREAD

**Issue by woutervanvliet** [zedzedzed/table-of-contents-plus#139]
I would like to be able to override the minimum number of headers that triggers the TOC to show from the shortcode.

**Comment by woutervanvliet** [comment]
Working on a solution, PR coming up real soon

**Comment by woutervanvliet** [comment]
Another solution I considered was to add an "force" attribute which would internally just set start to 1 to always force a toc as soon as there is a header. Thought behind this, is that it would seem to me that that's the use case which would be most common.

Let me know if you prefer the "force" attribute.

**Comment by zedzedzed** [comment]
Thank you for your contribution. I tried to merge but there were some conflicts as I had left it waayyyy tooooo long so I reapplied your changes.
