### ISSUE TITLE
Compatible with WP 5.6.1?

### ISSUE THREAD

**Issue by dhananjaygbhardwaj** [zedzedzed/table-of-contents-plus#142]
Hello @zedzedzed, really appreciate your work.

Although I personally haven't had any problems using the plugin on WP 5.6, I was wondering if you could confirm the same?

It would be great if this is reflected on the WordPress plugin page so that users who are looking for this great plugin do not get discouraged seeing the notice that says - "_This plugin hasn’t been tested with the latest 3 major releases of WordPress. It may no longer be maintained or supported and may have compatibility issues when used with more recent versions of WordPress._"

Thanks a lot!

**Comment by zedzedzed** [comment]
Hiya - thanks for the reminder. I don't have any issues with it on my multiple sites either but I have updated the tested on to 5.7 (beta) so it should flow through to the plugin listing.
