### ISSUE TITLE
Hide square brackets - how?

### ISSUE THREAD

**Issue by dajana91** [zedzedzed/table-of-contents-plus#149]
Hi,

how can you remove the unsightly brackets? So that there is no longer [ Show ] there, but only Show. I have not found a way to remove or hide them.

Greetings

**Comment by dajana91** [comment]
Does anyone have any ideas on how to accomplish this?

**Comment by zedzedzed** [comment]
Hello, there isn't a way to do it currently but I can surround those brackets with a CSS class and then you can add custom CSS to hide them.

Do you have a title for your table of contents? If you do, would it look funny if there was nothing separating it and show/close? Eg would it read `Table of contents show`?

**Comment by dajana91** [comment]
Hello, yes, it would be great to be able to address these square brackets via CSS and hide them, for example. For me, no title is displayed, but simply "Inhalt [anzeigen]", which means in English "[Show] Table of Content". I just want to be able to hide those square brackets, gladly via CSS. That would be great! Do you know when approximately such an update could come?

**Comment by zedzedzed** [comment]
I've just made the [changes](https://github.com/zedzedzed/table-of-contents-plus/commit/4973de317db43e53c3b7fbfcabb03554515d6e95) and it will be included in the next release. Should be by end of this month of by mid next month.

The CSS class is `toc_brackets` so something like this will hide them:

```css
.toc_brackets { display: none; }
```

**Comment by dajana91** [comment]
@zezzedzed Thank you very much, I am looking forward to it!

**Comment by dajana91** [comment]
@zedzedzed Hi, any news? You wrote that the update was supposed to appear at the end of last month or in the middle of this month. Unfortunately, it did not appear at the end of last month, nor now in the middle of the month.

**Comment by zedzedzed** [comment]
Hiya - it was released on 9 Feb as version 2302 and should have been available to you since then. It's appearing in the [wordpress repo](https://wordpress.org/plugins/table-of-contents-plus/#developers)

The CSS from above should hide the brackets.

**Comment by dajana91** [comment]
@zedzedzed  PS: I didn't use [no_toc] anywhere or anything like that. The table of contents used to appear right at the top of the article, since the update it has completely disappeared. I have now also checked all settings again - nothing helps.

**Comment by dajana91** [comment]
Ah, solution: For some reason, the update removed the settings in the "Advanced" section where you are supposed to select the headings to use for the table of contents (h1, h2, h3, h4, etc.). You had to manually re-enable all of them.
