### ISSUE TITLE
Fatal error – TOC+ Version 2309

### ISSUE THREAD

**Issue by archon810** [zedzedzed/table-of-contents-plus#157]
Hello,

In the newest plugin version there is a change to the way of loading files.

We have a very rare scenario – we need to load wp manually in one file in the active theme directory and this results in the fatal error because of the relative path in includes/init.php – require_once ‘functions.php’; which results in duplicate loading of the functions.php file in the theme direcrory instead of loading the functions.php in the init directory in the plugin.

Could you please change it to `require_once __DIR__ . ‘/functions.php’;`?

Similar to what you have in the toc.php

To test it just create test.php file in the theme dir and put something like this:

```
<?php

require_once(__DIR__ . '/../../../wp-load.php');

echo 'hello';
```

When you try to access it in the browser it will crash.

Thanks!

Originally, this ticket was filed here https://wordpress.org/support/topic/fatal-error-toc-version-2309/, but no response was received, so maybe you aren't checking the forums.

**Comment by zedzedzed** [comment]
Are you in a position to test the init.php changes at https://github.com/zedzedzed/table-of-contents-plus/blob/main/includes/init.php ?

**Comment by grasebit** [comment]
In my environment, the following error occurred.
2309

```
PHP Fatal error:  Uncaught Error: Undefined constant "STYLESHEETPATH" in /***/wp-includes/template.php:707

Stack trace:
#0 /***/wp-content/themes/theme-name/functions.php(6): locate_template()
#1 /***/wp-content/plugins/table-of-contents-plus/includes/init.php(6): require_once('...')
#2 /***/wp-content/plugins/table-of-contents-plus/toc.php(35): require_once('...')
#3 /***/wp-settings.php(462): include_once('...')
#4 /***/wp-config.php(93): require_once('...')
#5 /***/wp-load.php(50): require_once('...')
#6 /***/wp-content/themes/theme-name/st-rankcss.php(3): include_once('...')
#7 {main}

  thrown in /***/wp-includes/template.php on line 707, referer: https://***
```

I tried it on the master branch and the error went away.

**Comment by archon810** [comment]
@zedzedzed When is the next release with this fix in it please?

**Comment by zedzedzed** [comment]
About to push out a release right now :)
