### ISSUE TITLE
Feature "Allow the user to toggle the visibility of the table of contents" does not work

### ISSUE THREAD

**Issue by chyvak1831** [zedzedzed/table-of-contents-plus#166]
After latest update feature "Allow the user to toggle the visibility of the table of contents" does not work anymore: button 'show/hide' always missing on frontend
![image](https://github.com/zedzedzed/table-of-contents-plus/assets/11210100/81650d83-cc96-4ea1-b446-260f40e8bc0b)
![image](https://github.com/zedzedzed/table-of-contents-plus/assets/11210100/fde97274-8c84-4e66-91a0-d49b6e863bea)

tested on default themes, for example "Twenty Twenty-Four". Before latest updates this feature had been worked fine.

**Comment by zedzedzed** [comment]
The 2402 version changed the way CSS and JS were outputted. The next version will revert back to how 2311 operated and should fix this for you.

**Comment by chyvak1831** [comment]
Yeah, it's working great now!
Thank you so much!
