### ISSUE TITLE
Adoption option? 

### ISSUE THREAD

**Issue by rawrly** [zedzedzed/table-of-contents-plus#170]
Seeing the update update in the readme.txt I would like to discuss adoption of the plugin.

I am not looking to monetize the project, just looking to help reduce harm to users.

Let me know if you would like to discuss further. (sorry for posting this as an issue, I could not find a point of contact)

**Comment by zedzedzed** [comment]
Hi there, I've stepped back but the folks at plugins@wordpress.org have agreed to handle the adoption process so I'd suggest reach out to them.
